name: 'Lint & Test'
description: 'Run linters and tests on app or library'
inputs:
  path:
    required: true
    description: 'Path to the directory to lint and test'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Use cached project dependencies
      uses: ./.github/actions/cache-node-modules
    - name: Run lint
      run: |
        cd ${{ inputs.path }}
        yarn test-linter --max-warnings 0
      shell: bash
    - name: Run unit tests
      run: |
        cd ${{ inputs.path }}
        if [[ $(cat package.json | jq '.scripts["test-unit"]') != null ]]; then
          yarn test-unit
        else
          echo "No unit test script found in package.json"
        fi
      shell: bash
    - name: Run type test
      run: |
        cd ${{ inputs.path }}
        if [[ $(cat package.json | jq '.scripts["test-type"]') != null ]]; then
          yarn test-type
        else
          echo "No type test script found in package.json"
        fi
      shell: bash
    - name: Run circular dependencies test
      run: |
        cd ${{ inputs.path }}
        if [[ $(cat package.json | jq '.scripts["test-circular"]') != null ]]; then
          yarn test-circular
        else
          echo "No circular dependencies test script found in package.json"
        fi
      shell: bash
